server:
  port: 50100
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: config-service
  devtools:
    livereload:
      port: 51100
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ubaid4j/config-repo
          default-label: main
          timeout: 30
          clone-on-start: true
          force-pull: true
  lifecycle:
    timeout-per-shutdown-phase: 15s

#-----------------------Logging------------------------------#
logging:
  level:
    dev:
      ubaid: INFO
