apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: ghcr.io/ubaid4j/config-service:0.0.2-snapshot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50100
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 50100
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 50100
            initialDelaySeconds: 5
            periodSeconds: 15
          env:
            - name: SERVER_PORT
              value: "50100"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
